export { ReportsAnalyticsPage } from '../features/reports/ReportsPage.jsx';
export { TechnicianPanelPage } from '../features/technicians/TechnicianPanelPage.jsx';
export { AMCContractsPage } from '../features/workOrders/AMCContractsPage.jsx';
export { AMCSchedulePage } from '../features/workOrders/AMCSchedulePage.jsx';
export { AMCRenewalsPage } from '../features/workOrders/AMCRenewalsPage.jsx';
export { BookingsPage } from '../features/bookings/BookingsPage.jsx';
export { WorkOrdersPage } from '../features/workOrders/WorkOrdersPage.jsx';
export { WorkOrderDetailsPage } from '../features/workOrders/WorkOrderDetailsPage.jsx';
export { CustomersPage } from '../features/customers/CustomersPage.jsx';
export { CustomerProfilePage } from '../features/customers/CustomerProfilePage.jsx';
export { PaymentsPage } from '../features/payments/PaymentsPage.jsx';
export { TechnicianDashboard } from '../features/technicians/TechnicianDashboard.jsx';
export { InventoryPage } from '../features/inventory/InventoryPage.jsx';
export { StockMovementsPage } from '../features/inventory/StockMovementsPage.jsx';
export { InvoicesPage } from '../features/invoices/InvoicesPage.jsx';
export { DocumentsPage, CreateDocumentPage, DocumentPreviewPage } from '../features/invoices/DocumentsPage.jsx';
export { AuditLogsPage } from '../features/notifications/AuditLogsPage.jsx';
export { SystemSettingsPage } from '../features/settings/SettingsPage.jsx';